### ISSUE TITLE
Should work with @typescript-eslint/parser >= 5 as well

### ISSUE THREAD

**Issue by aaschmid** [a-tarasyuk/eslint-plugin-redundant-undefined#1]
I would love to use this in my project building a library but unfortunately this `eslint` plugin is not compatible with newer versions of `@typescript-eslint/parser` starting from `5.0`. Error message is 

```
> eslint .


Oops! Something went wrong! :(

ESLint: 8.1.0

TypeError: Failed to load plugin 'redundant-undefined' declared in '.eslintrc': Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/schmida/work/customer/son/fe-repo/node_modules/eslint-plugin-redundant-undefined/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (/Users/schmida/work/customer/son/fe-repo/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/Users/schmida/work/customer/son/fe-repo/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/schmida/work/customer/son/fe-repo/node_modules/eslint-plugin-redundant-undefined/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (/Users/schmida/work/customer/son/fe-repo/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by a-tarasyuk** [comment]
@aaschmid Thanks for the report. The latest [version 0.2.0](https://www.npmjs.com/package/eslint-plugin-redundant-undefined/v/0.2.0) should work with the latest `eslint` and `typescript-eslint`

**Comment by aaschmid** [comment]
Works like a charm, thanks for fixing!
